public enum Scenes
{
    DONT_DESTROY_ON_LOAD = -1,
    SCENELOADER,
    MENU,
    TEAM_READY,
    SONG_SELECT,
    TUTORIAL_CHOICE,
    LOADING,
    GAME,
    CALIBRATION_SERVEUR,
    MENU_SERVER,
    TEAM_SELECT_SERVER,
    SONG_SELECT_SERVER,
    GAME_SERVER,
    TRANSITION_SCENE,
    ENDGAME,
    EDITOR_SONG_SELECT,
    EDITOR,
    CREDIT,
    WAITING,
    INTRO,
    INTRO_SERVER
}
